/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view.manager.student;

import controller.StudentManager;
import entity.ExtraCurricularEntity;
import java.util.Vector;
import javax.swing.JOptionPane;
import model.ExtraCurricular;

/**
 *
 * @author luan
 */
public class ExtraCurricularUpdate extends javax.swing.JDialog {
    private ExtraCurricular curricular;
    private ExtraCurricularEntity entity;
    /**
     * Creates new form StudentMoreInfoDialog
     */
    public ExtraCurricularUpdate(java.awt.Frame parent, boolean modal, Vector data) {
        super(parent, modal);
        
        this.entity=new ExtraCurricularEntity();
        if(data!=null){
            this.curricular=new ExtraCurricular();
            curricular.setName(data.get(1).toString());
            curricular.setLocation(data.get(2).toString());
            curricular.setStart(entity.parseDate(data.get(3).toString()));
            curricular.setEnd(entity.parseDate(data.get(4).toString()));
            curricular.setNotes(data.get(5).toString());
        }
        initComponents();
        setLocationRelativeTo(this);
        initUI();
    }
    private void initUI(){
        if(curricular==null){
            return;
        }
        labelName.setText(curricular.getName());
        labelLocation.setText(curricular.getLocation());
        labelStart.setText(entity.formatDate(curricular.getStart()));
        labelEnd.setText(entity.formatDate(curricular.getEnd()));
        txtNotes.setText(curricular.getNotes());
        
    }
    private void chooser(){
        if(curricular==null){
            curricular=new ExtraCurricular();
        }
        ExtraCurricularChooser chooser=new ExtraCurricularChooser(null, true);
        chooser.setVisible(true);
        if(chooser.getChooser() >0){
            curricular=entity.findByID(chooser.getChooser());   
        }
        initUI();
    }
    private void save(){
        if(curricular==null){
            curricular=new ExtraCurricular();
        }
        if(curricular.getID()<=0){
            JOptionPane.showMessageDialog(this, "You must choose Extra Curricular !");
            return;
        }
        
        curricular.setNotes(txtNotes.getText());
        dispose();
        
    }

    public ExtraCurricular getExtraCurricular() {
        return curricular;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        labelName = new javax.swing.JLabel();
        btnChooser = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelLocation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelStart = new javax.swing.JTextField();
        labelEnd = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Notes");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel1.setText("Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 51, -1, -1));

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane2.setViewportView(txtNotes);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 270, -1));

        labelName.setText("Name");
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 51, -1, -1));

        btnChooser.setText("Choose");
        btnChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooserActionPerformed(evt);
            }
        });
        jPanel1.add(btnChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 45, -1, -1));

        jLabel2.setText("Location");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, -1, -1));

        labelLocation.setEnabled(false);
        jPanel1.add(labelLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 86, 160, -1));

        jLabel3.setText("Start");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel6.setText("End");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        labelStart.setEnabled(false);
        jPanel1.add(labelStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, -1));

        labelEnd.setEnabled(false);
        jPanel1.add(labelEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 410, 310));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel11.setText("Extra Curricular Update");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 16, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/20x20/save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/20x20/reset.gif"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        btnCancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/20x20/cancel.png"))); // NOI18N
        btnCancle.setText("Cancel");
        btnCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancle, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        initUI();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancleActionPerformed
        curricular=null;
        dispose();
    }//GEN-LAST:event_btnCancleActionPerformed

    private void btnChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooserActionPerformed
        chooser();
    }//GEN-LAST:event_btnChooserActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        curricular=null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancle;
    private javax.swing.JButton btnChooser;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField labelEnd;
    private javax.swing.JTextField labelLocation;
    private javax.swing.JLabel labelName;
    private javax.swing.JTextField labelStart;
    private javax.swing.JTextArea txtNotes;
    // End of variables declaration//GEN-END:variables
}
